export default {
    ON_LOGIN_SUCCESS: "ON_LOGIN_SUCCESS",
    ON_LOGIN_FAIL: "ON_LOGIN_FAIL",
    ON_LOGOUT: "ON_LOGOUT",
    ON_REGISTER_SUCCESS: "ON_REGISTER_SUCCESS",
    ON_REGISTER_FAIL: "ON_REGISTER_FAIL"
}
